# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuizApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuizApp

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics', '6.8.1'
pod 'Firebase/Auth'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

end
